### ISSUE TITLE
Filter by date

### ISSUE THREAD

**Issue by molusk** [g-coomans/Klassly_photos#1]
Hi,
Thank for your script, I have been able to download everything.
But now, there are new pictures available and if I run the script again, it downloads everything again...

Do you think there is a way to just get the new ones or to filter pictures publisshed earlier than the last downloaded ?

**Comment by g-coomans** [comment]
I update the script to download only the last photos from the last timestamp.
Download the new version and input your login/pwd + the timestamp from which you don't want to download photos. 

To calculate the timestamp, you can use [https://www.epochconverter.com/](https://www.epochconverter.com/)
The current timestamp is "1717382532". 

Thank you for your ticket :)
